# Generated by Django 5.1 on 2024-08-12 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='teams',
            new_name='team',
        ),
    ]
